export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/v1/auth/login",
    REGISTER: "/v1/auth/register",
    LOGOUT: "/v1/auth/logout",
    IMAGEKIT: "/v1/auth/imagekit",
  },
  ACCOUNT: {
    PROFILE: "/v1/account/update-profile",
    CHANGE_PASSWORD: "/v1/account/change-password",
    CHANGE_PROFILE: "/v1/account/change-profile-picture",
  },
  DASHBOARD: "/v1/dashboard/statistics",
  ARCHIVES: "/v1/archives",
  USERS: "/v1/users",
  ROLES: "/v1/roles",
  REQUESTS: "/v1/requests",
  EVENTS: "/v1/events",
  ATTENDANCES: "/v1/attendances",
  POSITIONS: "/v1/positions",
  CONTACTS: "/v1/contacts",
  HOTLINES: "/v1/hotlines",
  REQUEST_TYPES: "/v1/request-types",
  REPORTS: "/v1/reports",
  ATTACHMENTS: "/v1/attachments",
  GALLERIES: "/v1/galleries",
  GALLERY_IMAGES: "/v1/gallery-images",
  NOTIFICATIONS: "/v1/notifications",
  CHATS: "/v1/chats",
  PRIVATE_CHAT: "/v1/chat/privates",
  GROUP_CHAT: "/v1/chat/group-chats",
  PROVINCES: "/v1/locations/provinces",
  MUNICIPALITIES: "/v1/locations/municipalities",
  BARANGAYS: `/v1/locations/barangays/${import.meta.env.VITE_MUNICIPALITY_ID}`,
};

export const QUERY_KEYS = {
  ROLES: "roles",
  REQUESTS: "requests",
  APPROVAL_REQUESTS: "approval-requests",
  DASHBOARD: "/dashboard",
  ARCHIVES: "/archives",
  EVENTS: "events",
  ATTENDANCES: "attendances",
  POSITIONS: "positions",
  CONTACTS: "contacts",
  HOTLINES: "hotlines",
  PROVINCES: "provinces",
  MUNICIPALITIES: "municipalities",
  BARANGAYS: "barangays",
  REQUEST_TYPES: "request-types",
  USERS: "users",
  REPORTS: "reports",
  GALLERIES: "galleries",
  GALLERY_IMAGES: "gallery-images",
  NOTIFICATIONS: "/notifications",
  CHATS: "/chats",
  USER_PROFILE: "user-profile",
  PROFILE_PIC: "profile-pic",
};
