export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    IMAGEKIT: "/auth/imagekit",
  },
  ACCOUNT: {
    PROFILE: "/account/update-profile",
    CHANGE_PASSWORD: "/account/change-password",
    CHANGE_PROFILE: "/account/change-profile-picture",
  },
  USERS: "/users",
  ROLES: "/roles",
  REQUESTS: "/requests",
  EVENTS: "/events",
  ATTENDANCE: "/attendances",
  POSITIONS: "/positions",
  CONTACTS: "/contacts",
  HOTLINES: "/hotlines",
  REQUEST_TYPES: "/request-types",
  REPORTS: "/reports",
  ATTACHMENTS: "/attachments",
  GALLERIES: "/galleries",
  GALLERY_IMAGES: "/gallery-images",
  PROVINCES: "/locations/provinces",
  MUNICIPALITIES: "/locations/municipalities",
  BARANGAYS: `/locations/barangays/${import.meta.env.VITE_MUNICIPALITY_ID}`,
};

export const QUERY_KEYS = {
  ROLES: "roles",
  REQUESTS: "requests",
  EVENTS: "events",
  ATTENDANCES: "attendances",
  POSITIONS: "positions",
  CONTACTS: "contacts",
  HOTLINES: "hotlines",
  PROVINCES: "provinces",
  MUNICIPALITIES: "municipalities",
  BARANGAYS: "barangays",
  REQUEST_TYPES: "request-types",
  USERS: "users",
  REPORTS: "reports",
  GALLERIES: "galleries",
  USER_PROFILE: "user-profile",
  PROFILE_PIC: "profile-pic",
};
