/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as MainPositionsRouteImport } from './routes/_main/positions'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPositionsRoute = MainPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => MainRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/register': typeof authRegisterRoute
  '/dashboard': typeof MainDashboardRoute
  '/positions': typeof MainPositionsRoute
  '/': typeof authIndexRoute
}
export interface FileRoutesByTo {
  '/register': typeof authRegisterRoute
  '/dashboard': typeof MainDashboardRoute
  '/positions': typeof MainPositionsRoute
  '/': typeof authIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/(auth)/register': typeof authRegisterRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/positions': typeof MainPositionsRoute
  '/(auth)/': typeof authIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/register' | '/dashboard' | '/positions' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/register' | '/dashboard' | '/positions' | '/'
  id:
    | '__root__'
    | '/_main'
    | '/(auth)/register'
    | '/_main/dashboard'
    | '/_main/positions'
    | '/(auth)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  authRegisterRoute: typeof authRegisterRoute
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/positions': {
      id: '/_main/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof MainPositionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteChildren {
  MainDashboardRoute: typeof MainDashboardRoute
  MainPositionsRoute: typeof MainPositionsRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDashboardRoute: MainDashboardRoute,
  MainPositionsRoute: MainPositionsRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  authRegisterRoute: authRegisterRoute,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
