import { ROLES } from "@/lib/constants";
import type { SidebarItemProps } from "@/types";
import {
  AlbumIcon,
  AlignEndHorizontalIcon,
  CalendarIcon,
  CardSimIcon,
  FileChartColumnIcon,
  HeadsetIcon,
  ImageIcon,
  LandPlotIcon,
  LayoutGridIcon,
  ServerIcon,
  UsersIcon,
} from "lucide-react";

export const items: SidebarItemProps[] = [
  {
    title: "Dashboard",
    url: "/dashboard",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.USER],
    icon: LayoutGridIcon,
    isActive: true,
  },
  {
    title: "Requests",
    url: "/requests",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.USER],
    icon: ServerIcon,
    isActive: false,
  },
  {
    title: "Events",
    url: "/events",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.USER],
    icon: CalendarIcon,
    isActive: false,
  },
  {
    title: "Galleries",
    url: "/galleries",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.USER],
    icon: ImageIcon,
    isActive: false,
  },
  {
    title: "Attendances",
    url: "/attendances",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.USER],
    icon: LandPlotIcon,
    isActive: false,
  },
  {
    title: "Reports",
    url: "/reports",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN, ROLES.USER],
    icon: FileChartColumnIcon,
    isActive: false,
  },
  {
    title: "SK Members",
    url: "/users",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN],
    icon: UsersIcon,
    isActive: false,
  },
  {
    title: "Positions",
    url: "/positions",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN],
    icon: AlignEndHorizontalIcon,
    isActive: false,
  },
  {
    title: "Request Types",
    url: "/request-types",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN],
    icon: AlbumIcon,
    isActive: false,
  },
  {
    title: "Hotlines",
    url: "/hotlines",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN],
    icon: HeadsetIcon,
    isActive: false,
  },
  {
    title: "Contacts",
    url: "/contacts",
    authorize: [ROLES.SUPERADMIN, ROLES.ADMIN],
    icon: CardSimIcon,
    isActive: false,
  },
];
